name: poc_hybrid_app_grpc_client
description: Demo hybrid app with gRPC and REST capabilities.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.1.4 <4.0.0"
dependencies:
  http: ^1.1.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  grpc: ^3.2.4
  protobuf: ^3.1.0
  pluto_grid: ^7.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
